### ISSUE TITLE
Fatal error: Declaration of WebmanTech\Polyfill\Traits\SymfonyRequestWrapper::createFromGlobals() must be compatible with Symfony\Component\HttpFoundation\Request::createFromGlobals():

### ISSUE THREAD

**Issue by van-chin** [krissss/webman-polyfill#1]
```php
use support\Request;
use WebmanTech\Polyfill\LaravelRequest;


$requestWrapper = LaravelRequest::wrapper($request);




```

Fatal error: Declaration of WebmanTech\Polyfill\Traits\SymfonyRequestWrapper::createFromGlobals() must be compatible with Symfony\Component\HttpFoundation\Request::createFromGlobals(): static in /app/xxx-dir/vendor/webman-tech/polyfill/src/Traits/SymfonyRequestWrapper.php on line 37
Worker[171] process terminated with ERROR: E_COMPILE_ERROR "Declaration of WebmanTech\Polyfill\Traits\SymfonyRequestWrapper::createFromGlobals() must be compatible with Symfony\Component\HttpFoundation\Request::createFromGlobals(): static in /app/xxx-dir/vendor/webman-tech/polyfill/src/Traits/SymfonyRequestWrapper.php on line 37"
worker[webman:171] exit with status 65280

**Comment by krissss** [comment]
which laravel version and php version

**Comment by krissss** [comment]
please update `composer require webman-tech/polyfill`

**Comment by van-chin** [comment]
@krissss  thanks! upgrade  `webman-tech/polyfill` to  v1.0.1, it's ok
